PREFIX cpm: <https://w3id.org/corruptpm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?phase ?phaseLabel ?risk ?riskLabel
WHERE {
  ?phase rdfs:subClassOf cpm:ProjectPhase ;
         rdfs:subClassOf ?restriction .
  FILTER (?phase != cpm:ProjectPhase)
  ?restriction a owl:Restriction ;
               owl:onProperty cpm:hasRiskFactor ;
               owl:someValuesFrom ?risk .
  OPTIONAL { ?phase rdfs:label ?phaseLabel }
  OPTIONAL { ?risk rdfs:label ?riskLabel }
}
ORDER BY ?phaseLabel ?riskLabel

