PREFIX cpm: <https://w3id.org/corruptpm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?act ?actLabel ?property ?control ?controlLabel
WHERE {
  VALUES ?act { cpm:BidRigging }
  ?act rdfs:subClassOf ?restriction .
  ?restriction a owl:Restriction ;
               owl:onProperty ?property ;
               owl:someValuesFrom ?control .
  VALUES ?property { cpm:isMitigatedBy cpm:isDetectedBy cpm:isPreventedBy }
  OPTIONAL { ?act rdfs:label ?actLabel }
  OPTIONAL { ?control rdfs:label ?controlLabel }
}
ORDER BY ?property ?controlLabel

