PREFIX cpm: <https://w3id.org/corruptpm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?impact ?impactLabel
WHERE {
  VALUES ?act { cpm:VariationOrderManipulation }
  ?act rdfs:subClassOf ?restriction .
  ?restriction a owl:Restriction ;
               owl:onProperty cpm:hasImpact ;
               owl:someValuesFrom ?impact .
  OPTIONAL { ?impact rdfs:label ?impactLabel }
}
ORDER BY ?impactLabel

