PREFIX cpm: <https://w3id.org/corruptpm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?stage ?stageLabel ?risk ?riskLabel
WHERE {
  ?stage rdfs:subClassOf cpm:ContractStage ;
         rdfs:subClassOf ?restriction .
  FILTER (?stage != cpm:ContractStage)
  ?restriction a owl:Restriction ;
               owl:onProperty cpm:hasRiskFactor ;
               owl:someValuesFrom ?risk .
  OPTIONAL { ?stage rdfs:label ?stageLabel }
  OPTIONAL { ?risk rdfs:label ?riskLabel }
}
ORDER BY ?stageLabel ?riskLabel

