PREFIX cpm: <https://w3id.org/corruptpm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?phase ?phaseLabel ?property ?control ?controlLabel
WHERE {
  ?phase rdfs:subClassOf cpm:ProjectPhase ;
         rdfs:subClassOf ?restriction .
  FILTER (?phase != cpm:ProjectPhase)
  ?restriction a owl:Restriction ;
               owl:onProperty ?property ;
               owl:someValuesFrom ?control .
  VALUES ?property { cpm:isMitigatedBy cpm:isDetectedBy }
  OPTIONAL { ?phase rdfs:label ?phaseLabel }
  OPTIONAL { ?control rdfs:label ?controlLabel }
}
ORDER BY ?phaseLabel ?controlLabel

