PREFIX cpm: <https://w3id.org/corruptpm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?risk ?riskLabel
WHERE {
  cpm:LandAcquisitionAndCompensationPhase rdfs:subClassOf ?restriction .
  ?restriction a owl:Restriction ;
               owl:onProperty ?property ;
               owl:someValuesFrom ?risk .
  VALUES ?property { cpm:hasRiskFactor cpm:hasVulnerability }
  OPTIONAL { ?risk rdfs:label ?riskLabel }
}
ORDER BY ?riskLabel

