PREFIX cpm: <https://w3id.org/corruptpm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?redFlag ?redFlagLabel
WHERE {
  cpm:BidRigging rdfs:subClassOf ?restriction .
  ?restriction a owl:Restriction ;
               owl:onProperty cpm:hasRedFlag ;
               owl:someValuesFrom ?redFlag .
  OPTIONAL { ?redFlag rdfs:label ?redFlagLabel }
}
ORDER BY ?redFlagLabel
